Updated script to include support for docker command
keploy/testGPT pull request #2
Opened 2024-02-08 13:25 UTC by Akash-Singh04

Fixes:#1505 https://github.com/keploy/keploy/issues/1505

## Description

This PR modifies the script to include support for running Docker commands specifically for the `keploy test` step. It ensures there is support for Docker Commands.

## Changes Made

- If the provided command includes "docker", it directly executes the Docker command specified in the `$COMMAND` variable.
- The `keploy test` command is constructed using the Docker command specified in the `$COMMAND` variable, along with other parameters.

### Reason for Change:

The current support is for only java.js,go,py, hence by adding docker command support, we help in running keploy test run with other frameworks including the above ones.

2024-02-12 12:05 UTC, Akash-Singh04 commented
@Sonichigo Kindly review this

2024-02-13 13:17 UTC, Sonichigo approved these changes

2024-02-13 13:17 UTC, Sonichigo commented on install.sh
>    sudo -E keploy test -c "${COMMAND}" --delay ${DELAY} --path "${KEPLOY_PATH}"
In case of Docker command usage `--delay` would be replaced by `--buildDelay` .  Also, In the case of `docker-compose`, you would need to pass `--containerName` as well.

2024-02-13 13:17 UTC, Sonichigo commented on install.sh
> -echo curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
is there any specifics to remove `echo` ?

2024-02-13 13:19 UTC, Sonichigo requested changes

2024-02-13 13:19 UTC, Sonichigo commented on install.sh
> -echo curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
they are used to see the flow of action in github actions and debug if any steps are missing/not working

2024-02-13 16:56 UTC, SkySingh04 commented on install.sh
> -echo curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
Understood, I've added it back

2024-02-13 16:56 UTC, Akash-Singh04 commented on install.sh
>    sudo -E keploy test -c "${COMMAND}" --delay ${DELAY} --path "${KEPLOY_PATH}"
Refactored

2024-02-14 05:33 UTC, Sonichigo commented
The issue for which this PR was raised has been solved by this #3 PR. So resolving the issue and closing this pr.

2024-02-14 05:33 UTC, closed without merging